# Generated by Django 2.2.15 on 2020-08-07 11:23

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('enterprise_customer', models.UUIDField(help_text='UUID for an EnterpriseCustomer from the Enterprise Service.')),
                ('email_type', models.CharField(choices=[('assign', 'Assign'), ('remind', 'Remind'), ('revoke', 'Revoke')], max_length=32)),
                ('email_subject', models.TextField()),
                ('email_greeting', models.TextField(blank=True, null=True)),
                ('email_closing', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Make a particular template version active.')),
            ],
            options={
                'ordering': ('enterprise_customer', '-active'),
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['enterprise_customer', 'email_type'], name='email_templ_enterpr_6d61c6_idx'),
        ),
    ]
