[tox]
envlist = py312-django{42,52}, quality, docs, pii_check
requires =
    tox-uv>=1
skipsdist = true

[doc8]
; D001 = Line too long
ignore = D001

[pycodestyle]
# E501: Line too long (80 chars)
# W503: Line break occurred before a binary operator
# E261: At least two spaces before inline comment
ignore = E501,W503,E261
max-line-length = 120
exclude = .git,settings,migrations,license_manager/static,bower_components,license_manager/wsgi.py

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
setenv =
    DJANGO_SETTINGS_MODULE = license_manager.settings.test
commands =
    pytest {posargs}

[testenv:translations]
runner = uv-venv-lock-runner
dependency_groups =
    dev
allowlist_externals =
    make
commands =
    make validate_translations

[testenv:docs]
runner = uv-venv-lock-runner
dependency_groups =
    doc
setenv =
    DJANGO_SETTINGS_MODULE = license_manager.settings.test
    PYTHONPATH = {toxinidir}
    SPHINXOPTS = -W
allowlist_externals =
    make
    rm
commands =
    doc8 --ignore-path docs/_build README.rst docs
    rm -f docs/license_manager.rst
    rm -f docs/modules.rst
    make -e -C docs clean
    make -e -C docs html

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups =
    quality
allowlist_externals =
    make
commands =
    make quality

[testenv:pii_check]
runner = uv-venv-lock-runner
dependency_groups =
    test
setenv =
    DJANGO_SETTINGS_MODULE = license_manager.settings.test
allowlist_externals =
    make
commands =
    make pii_check
