# Generated by Django 2.2.12 on 2020-05-26 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('enterprise_customer_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('enterprise_catalog_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscriptionPlan',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('enterprise_customer_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('enterprise_catalog_uuid', models.UUIDField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Subscription Plan',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLicense',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('deactivated', 'Deactivated')], default='unassigned', help_text='The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has enrolled in a course with that license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not been used by that learner to enroll in a course since the time of assignment.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nDeactivated: A license which has been created but is no longer active (intentionally made inactive or has expired). A license in this state may or may not have a learner assigned.', max_length=25)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_remind_date', models.DateTimeField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lms_user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.SubscriptionPlan')),
            ],
            options={
                'verbose_name': 'historical license',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('deactivated', 'Deactivated')], default='unassigned', help_text='The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has enrolled in a course with that license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not been used by that learner to enroll in a course since the time of assignment.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nDeactivated: A license which has been created but is no longer active (intentionally made inactive or has expired). A license in this state may or may not have a learner assigned.', max_length=25)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('last_remind_date', models.DateTimeField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lms_user_id', models.IntegerField(blank=True, null=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='subscriptions.SubscriptionPlan')),
            ],
            options={
                'unique_together': {('subscription_plan', 'user_email'), ('subscription_plan', 'lms_user_id')},
            },
        ),
    ]
