# Generated by Django 2.2.12 on 2020-05-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('subscription_plan', 'user_email'), ('subscription_plan', 'lms_user_id')},
        ),
    ]
