# Generated by Django 2.2.12 on 2020-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20200529_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='expiration_date',
            field=models.DateField(default='2021-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='purchase_date',
            field=models.DateField(default='2020-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='start_date',
            field=models.DateField(default='2020-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='expiration_date',
            field=models.DateField(default='2021-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='purchase_date',
            field=models.DateField(default='2020-06-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='start_date',
            field=models.DateField(default='2020-06-05'),
            preserve_default=False,
        ),
    ]
