# Generated by Django 2.2.12 on 2020-06-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_require_date_fields_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='title',
            field=models.CharField(default='Title', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='title',
            field=models.CharField(default='Title', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('title', 'enterprise_customer_uuid')},
        ),
    ]
