# Generated by Django 2.2.13 on 2020-06-30 18:05

from django.db import migrations, models


from license_manager.apps.subscriptions.constants import SUBSCRIPTIONS_LEARNER_ROLE


def create_roles(apps, schema_editor):
    """
    Create the enterprise subscriptions roles if they do not already exist.
    """
    SubscriptionsFeatureRole = apps.get_model('subscriptions', 'SubscriptionsFeatureRole')
    SubscriptionsFeatureRole.objects.update_or_create(name=SUBSCRIPTIONS_LEARNER_ROLE)


def delete_roles(apps, schema_editor):
    """
    Delete the enterprise subscriptions roles.
    """
    SubscriptionsFeatureRole = apps.get_model('subscriptions', 'SubscriptionsFeatureRole')
    SubscriptionsFeatureRole.objects.filter(name=SUBSCRIPTIONS_LEARNER_ROLE).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptions_feature_roles'),
    ]

    operations = [
        migrations.RunPython(create_roles, delete_roles),
    ]
