# Generated by Django 2.2.13 on 2020-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscriptions_feature_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('subscription_plan', 'user_email', 'status', 'revoked_date'), ('subscription_plan', 'lms_user_id')},
        ),
    ]
