# Generated by Django 2.2.13 on 2020-07-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_add_netsuite_and_salesforce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='for_internal_use_only',
            field=models.BooleanField(default=False, help_text='Whether this SubscriptionPlan is only for internal use (e.g. a test Subscription record).'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='for_internal_use_only',
            field=models.BooleanField(default=False, help_text='Whether this SubscriptionPlan is only for internal use (e.g. a test Subscription record).'),
        ),
    ]
