# Generated by Django 2.2.13 on 2020-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_add_subsc_for_internal_use_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='activation_key',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='activation_key',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True),
        ),
    ]
