# Generated by Django 2.2.15 on 2020-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_add_activation_key_to_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallicense',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='revoked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
