# Generated by Django 2.2.16 on 2020-09-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_change_deactivated_status_to_revoked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='purchase_date',
        ),
    ]
