# Generated by Django 2.2.16 on 2020-10-28 18:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0013_add_revoke_cap_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('salesforce_opportunity_id', models.CharField(help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters). Note that this is not the same Salesforce Opportunity ID associated with the linked subscription.', max_length=18, validators=[django.core.validators.MinLengthValidator(18)])),
                ('number_of_licenses', models.PositiveIntegerField(help_text='Number of licenses to renew the linked subscription for.')),
                ('effective_date', models.DateField(help_text='The date that the subscription renewal will take place on.')),
                ('renewed_expiration_date', models.DateField(help_text='The date that the renewed subscription should expire on.')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='subscriptions.SubscriptionPlan')),
            ],
            options={
                'verbose_name': 'Subscription Plan Renewal',
                'verbose_name_plural': 'Subscription Plan Renewals',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubscriptionPlanRenewal',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('salesforce_opportunity_id', models.CharField(help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters). Note that this is not the same Salesforce Opportunity ID associated with the linked subscription.', max_length=18, validators=[django.core.validators.MinLengthValidator(18)])),
                ('number_of_licenses', models.PositiveIntegerField(help_text='Number of licenses to renew the linked subscription for.')),
                ('effective_date', models.DateField(help_text='The date that the subscription renewal will take place on.')),
                ('renewed_expiration_date', models.DateField(help_text='The date that the renewed subscription should expire on.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.SubscriptionPlan')),
            ],
            options={
                'verbose_name': 'historical Subscription Plan Renewal',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
