# Generated by Django 2.2.16 on 2020-10-30 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_add_revoke_cap_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True, unique=True)),
                ('enterprise_customer_slug', models.CharField(blank=True, max_length=128, null=True)),
                ('default_enterprise_catalog_uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer Subscription',
                'verbose_name_plural': 'Customer Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlanType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='customer_subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.CustomerSubscription'),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='subscription_plan_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.SubscriptionPlanType'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='customer_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='subscriptions.CustomerSubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription_plan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_plans', to='subscriptions.SubscriptionPlanType'),
        ),
    ]
