# Generated by Django 2.2.16 on 2020-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_add_subscriptionplanrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplanrenewal',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether the renewal has been processed and gone into effect for the linked subscription.'),
        ),
        migrations.AddField(
            model_name='subscriptionplanrenewal',
            name='processed',
            field=models.BooleanField(default=False, help_text='Whether the renewal has been processed and gone into effect for the linked subscription.'),
        ),
    ]
