# Generated by Django 2.2.17 on 2020-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_create_customer_agreements'),
    ]

    operations = [
        # We don't have any subscriptions in stage or production with NULL `enterprise_catalog_uuid` so this one time
        # default is for setting old history rows and providing a local development convenience 
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='enterprise_catalog_uuid',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='enterprise_catalog_uuid',
            field=models.UUIDField(default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
    ]
