# Generated by Django 2.2.17 on 2021-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_remove_enterprise_customer_uuid_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='expiration_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='expiration_processed',
            field=models.BooleanField(default=False),
        ),
    ]
