# Generated by Django 2.2.17 on 2021-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_add_expiration_processed_to_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragreement',
            name='default_enterprise_catalog_uuid',
            field=models.UUIDField(blank=True, help_text='The default enterprise catalog UUID must be from a catalog associated with the above Enterprise Customer UUID.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomeragreement',
            name='default_enterprise_catalog_uuid',
            field=models.UUIDField(blank=True, help_text='The default enterprise catalog UUID must be from a catalog associated with the above Enterprise Customer UUID.', null=True),
        ),
    ]
