# Generated by Django 2.2.19 on 2021-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_subscriptionsroleassignment_applies_to_all_contexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('is_paid_subscription', models.BooleanField(default=True)),
                ('ns_id_required', models.BooleanField(default=True)),
                ('sf_id_required', models.BooleanField(default=True)),
                ('internal_use_only', models.BooleanField(default=False)),
            ],
        ),
    ]
