# Generated by Django 2.2.19 on 2021-05-27 18:48

from django.db import migrations


def generate_base_plan_types(apps, schema_editor):
    SubscriptionPlanType = apps.get_model("subscriptions", "PlanType")
    SubscriptionPlanType.objects.get_or_create(
        label='Standard Paid',
        description='A paid subscription plan',
        is_paid_subscription=True,
        ns_id_required=True,
        sf_id_required=True,
        internal_use_only=False,
    )
    SubscriptionPlanType.objects.get_or_create(
        label='OCE',
        description='Online Campus Essentials, unpaid subscription plan for academic institutions',
        is_paid_subscription=False,
        ns_id_required=False,
        sf_id_required=True,
        internal_use_only=False,
    )
    SubscriptionPlanType.objects.get_or_create(
        label='Trial',
        description='Limited free subscription plan for prospective customers',
        is_paid_subscription=False,
        ns_id_required=False,
        sf_id_required=True,
        internal_use_only=False,
    )
    SubscriptionPlanType.objects.get_or_create(
        label='Test',
        description='Internal edX subscription testing',
        is_paid_subscription=False,
        ns_id_required=False,
        sf_id_required=False,
        internal_use_only=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_plantype'),
    ]

    operations = [
        migrations.RunPython(generate_base_plan_types),
    ]
