# Generated by Django 2.2.23 on 2021-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_new_renewals_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='disable_expiration_notifications',
            field=models.BooleanField(default=False, help_text='Used in MFEs to disable subscription expiration notifications'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='disable_expiration_notifications',
            field=models.BooleanField(default=False, help_text='Used in MFEs to disable subscription expiration notifications'),
        ),
    ]
