# Generated by Django 2.2.23 on 2021-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_auto_20210608_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='is_revocation_cap_enabled',
            field=models.BooleanField(default=False, help_text='Determines whether there is a maximum cap on the number of license revocations for this SubscriptionPlan. Defaults to False.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_revocation_cap_enabled',
            field=models.BooleanField(default=False, help_text='Determines whether there is a maximum cap on the number of license revocations for this SubscriptionPlan. Defaults to False.'),
        ),
    ]
