# Generated by Django 2.2.23 on 2021-06-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0027_renewal_cap_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantype',
            name='internal_use_only',
            field=models.BooleanField(default=False, help_text='Marking this indicates this subscription is only used internally by edX employees.'),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='is_paid_subscription',
            field=models.BooleanField(default=True, help_text='Marking this indicates that the plan is a paid subscription.'),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='ns_id_required',
            field=models.BooleanField(default=True, help_text='Marking this indicates the NetSuite ID is required.'),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='sf_id_required',
            field=models.BooleanField(default=True, help_text='Marking this indicates the Salesforce ID is required.'),
        ),
    ]
