# Generated by Django 2.2.23 on 2021-06-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0029_populate_plan_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='renewed_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.License'),
        ),
        migrations.AddField(
            model_name='license',
            name='renewed_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_renewed_from', to='subscriptions.License'),
        ),
        migrations.AlterField(
            model_name='historicallicense',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('revoked', 'Revoked')], default='unassigned', help_text="The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has activated the license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not yet been activated by that learner.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nRevoked: A license which has been created but is no longer active (intentionally revoked or has expired). A license in this state may or may not have a learner assigned.\nTransferred for renwal: The license's subscription plan was renewed into a new plan, and the license transferred to a new, active license in the renewed plan.", max_length=25),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('revoked', 'Revoked')], default='unassigned', help_text="The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has activated the license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not yet been activated by that learner.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nRevoked: A license which has been created but is no longer active (intentionally revoked or has expired). A license in this state may or may not have a learner assigned.\nTransferred for renwal: The license's subscription plan was renewed into a new plan, and the license transferred to a new, active license in the renewed plan.", max_length=25),
        ),
    ]
