# Generated by Django 2.2.23 on 2021-06-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_add_license_renewal_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext_template', models.TextField()),
                ('html_template', models.TextField()),
                ('subject_line', models.CharField(max_length=100)),
                ('template_type', models.TextField()),
                ('plan_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.PlanType')),
            ],
        ),
    ]
