# Generated by Django 2.2.24 on 2021-07-29 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0033_auto_20210726_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='netsuite_product_id',
            field=models.IntegerField(blank=True, help_text='Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters).', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='netsuite_product_id',
            field=models.IntegerField(blank=True, help_text='Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters).', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
    ]
