# Generated by Django 2.2.24 on 2021-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0034_auto_20210729_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='can_freeze_unused_licenses',
            field=models.BooleanField(default=False, help_text='Whether this Subscription Plan supports freezing licenses, where unused licenses (not including previously revoked licenses) are deleted.'),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='last_freeze_timestamp',
            field=models.DateTimeField(blank=True, help_text='The time at which the Subscription Plan was last frozen.', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_freeze_unused_licenses',
            field=models.BooleanField(default=False, help_text='Whether this Subscription Plan supports freezing licenses, where unused licenses (not including previously revoked licenses) are deleted.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='last_freeze_timestamp',
            field=models.DateTimeField(blank=True, help_text='The time at which the Subscription Plan was last frozen.', null=True),
        ),
    ]
