# Generated by Django 2.2.24 on 2021-08-04 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0035_freeze_unused_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='license_duration_before_purge',
            field=models.DurationField(default=datetime.timedelta(days=90), help_text='The number of days after which unclaimed, revoked, or expired (due to plan expiration) licenses associated with this customer agreement will have user data retired and the license status reset to UNASSIGNED.'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='license_duration_before_purge',
            field=models.DurationField(default=datetime.timedelta(days=90), help_text='The number of days after which unclaimed, revoked, or expired (due to plan expiration) licenses associated with this customer agreement will have user data retired and the license status reset to UNASSIGNED.'),
        ),
    ]
