# Generated by Django 2.2.24 on 2021-08-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0036_add_license_duration_before_purge_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='for_internal_use_only',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='for_internal_use_only',
        ),
    ]
