# Generated by Django 2.2.24 on 2021-08-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0037_alter_agreement_slug_allow_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='for_internal_use_only',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='for_internal_use_only',
        ),
    ]
