# Generated by Django 2.2.24 on 2021-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0037_alter_agreement_slug_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='effective_date',
            field=models.DateTimeField(help_text='The date that the subscription renewal will take place on.'),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='renewed_expiration_date',
            field=models.DateTimeField(help_text='The date that the renewed subscription should expire on.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='effective_date',
            field=models.DateTimeField(help_text='The date that the subscription renewal will take place on.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='renewed_expiration_date',
            field=models.DateTimeField(help_text='The date that the renewed subscription should expire on.'),
        ),
    ]
