# Generated by Django 2.2.24 on 2021-09-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0038_alter_datefield_to_datetimefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallicense',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('revoked', 'Revoked')], default='unassigned', help_text='The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has activated the license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not yet been activated by that learner.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nRevoked: A license which has been created but is no longer active (intentionally revoked or has expired). A license in this state may or may not have a learner assigned.', max_length=25),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('revoked', 'Revoked')], default='unassigned', help_text='The status fields has the following options and definitions:\nActive: A license which has been created, assigned to a learner, and the learner has activated the license. The license also must not have expired.\nAssigned: A license which has been created and assigned to a learner, but which has not yet been activated by that learner.\nUnassigned: A license which has been created but does not have a learner assigned to it.\nRevoked: A license which has been created but is no longer active (intentionally revoked or has expired). A license in this state may or may not have a learner assigned.', max_length=25),
        ),
    ]
