# Generated by Django 3.2.7 on 2021-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0039_auto_20210920_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='enterprise_customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='enterprise_customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
