# Generated by Django 3.2.8 on 2021-10-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0040_add_enterprise_customer_name_to_customer_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enterprise_customer_uuid', models.UUIDField(verbose_name='Enterprise Customer UUID')),
                ('enterprise_customer_user_uuid', models.UUIDField(verbose_name='Enterprise Customer User UUID')),
                ('notification_type', models.CharField(choices=[('limited_allocations_remaining', 'Limited Allocations Remaining'), ('no_allocations_remaining', 'No Allocations Remaining'), ('periodic_informational', 'Periodic Informational')], help_text='Which type of notification was sent to the user.', max_length=32)),
                ('last_sent', models.DateTimeField(help_text='Date of the last time a notifcation was sent.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enterprise_customer_uuid', models.UUIDField(verbose_name='Enterprise Customer UUID')),
                ('enterprise_customer_user_uuid', models.UUIDField(verbose_name='Enterprise Customer User UUID')),
                ('notification_type', models.CharField(choices=[('limited_allocations_remaining', 'Limited Allocations Remaining'), ('no_allocations_remaining', 'No Allocations Remaining'), ('periodic_informational', 'Periodic Informational')], help_text='Which type of notification was sent to the user.', max_length=32)),
                ('last_sent', models.DateTimeField(help_text='Date of the last time a notifcation was sent.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical notification',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
