# Generated by Django 3.2.8 on 2021-10-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0041_historicalnotification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicense',
            name='auto_applied',
            field=models.BooleanField(blank=True, help_text='Whether or not License was auto-applied.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='auto_applied',
            field=models.BooleanField(blank=True, help_text='Whether or not License was auto-applied.', null=True),
        ),
    ]
