# Generated by Django 3.2.9 on 2021-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0043_auto_20211022_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplanrenewal',
            name='disable_auto_apply_licenses',
            field=models.BooleanField(default=False, help_text='Whether auto-applied licenses should be disabled for the future plan. If the original plan was not auto applying licenses, modifying this field will have no effect.'),
        ),
        migrations.AddField(
            model_name='subscriptionplanrenewal',
            name='disable_auto_apply_licenses',
            field=models.BooleanField(default=False, help_text='Whether auto-applied licenses should be disabled for the future plan. If the original plan was not auto applying licenses, modifying this field will have no effect.'),
        ),
    ]
