# Generated by Django 3.2.9 on 2021-11-09 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0044_auto_20211104_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotification',
            name='subscripton_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subscripton_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='historicalnotification',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of the last time a notifcation was sent.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of the last time a notifcation was sent.'),
        ),
    ]
