# Generated by Django 3.2.9 on 2021-11-10 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0045_auto_20211109_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='netsuite_product_id',
            field=models.IntegerField(blank=True, help_text='DEPRECATED in favor product.netsuite_id. Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='plan_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='DEPRECATED in favor product.plan_type. Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.plantype'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='netsuite_product_id',
            field=models.IntegerField(blank=True, help_text='DEPRECATED in favor product.netsuite_id. Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.ForeignKey(help_text='DEPRECATED in favor product.plan_type. Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.plantype'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('netsuite_id', models.IntegerField(blank=True, help_text='The Product ID field (numeric) of what was sold to the customer.', null=True)),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='netsuite_products', to='subscriptions.plantype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('netsuite_id', models.IntegerField(blank=True, help_text='The Product ID field (numeric) of what was sold to the customer.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.plantype')),
            ],
            options={
                'verbose_name': 'historical product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.product'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.product'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('netsuite_id',), name='unique_netsuite_id'),
        ),
    ]
