# Generated by Django 3.2.9 on 2021-11-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0047_populate_subscription_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='netsuite_product_id',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='netsuite_product_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.product'),
        ),
    ]
