# Generated by Django 3.2.9 on 2021-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0048_delete_planemailtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='disable_onboarding_notifications',
            field=models.BooleanField(default=False, help_text='Used to disable onboarding notifications, i.e. license assignment and post-activation emails.'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='disable_onboarding_notifications',
            field=models.BooleanField(default=False, help_text='Used to disable onboarding notifications, i.e. license assignment and post-activation emails.'),
        ),
    ]
