# Generated by Django 3.2.9 on 2021-12-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0049_add_disable_onboarding_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED in favor product.plan_type. Locate the Sales Order record in NetSuite and copy the Product ID field (numeric).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subscriptions.plantype'),
        ),
    ]
