# Generated by Django 3.2.15 on 2022-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0053_auto_20220301_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='salesforce_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salesforce_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
