# Generated by Django 3.2.19 on 2023-05-30 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0055_auto_20220916_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplan',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, help_text='Locate the appropriate Salesforce Opportunity Line Item record and copy the Opportunity Product field (18 characters).', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, help_text='Locate the appropriate Salesforce Opportunity Line Item record and copy the Opportunity Product field (18 characters).', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Deprecated 18 character value, derived from Salesforce Opportunity record and copied to the Opportunity ID field.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Deprecated 18 character value, derived from Salesforce Opportunity record and copied to the Opportunity ID field.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
    ]
