# Generated by Django 3.2.21 on 2023-09-15 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0056_auto_20230530_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Deprecated -- 18 character value, derived from Salesforce Opportunity record.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, help_text='18 character value -- Locate the appropriate Salesforce Opportunity Line Item record and copy it here.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='salesforce_opportunity_id',
            field=models.CharField(help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters). Note that this is not the same Salesforce Opportunity ID associated with the linked subscription.', max_length=18, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='Salesforce Opportunity Line Item'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Deprecated -- 18 character value, derived from Salesforce Opportunity record.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='salesforce_opportunity_line_item',
            field=models.CharField(blank=True, help_text='18 character value -- Locate the appropriate Salesforce Opportunity Line Item record and copy it here.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)]),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='salesforce_opportunity_id',
            field=models.CharField(help_text='Locate the appropriate Salesforce Opportunity record and copy the Opportunity ID field (18 characters). Note that this is not the same Salesforce Opportunity ID associated with the linked subscription.', max_length=18, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='Salesforce Opportunity Line Item'),
        ),
    ]
