# Generated by Django 3.2.21 on 2023-09-18 04:32

from django.db import migrations


LICENSE_SOURCE_TYPES = {
    'Application Management Technology': 'AMT'
}


def add_license_source_types(apps, schema_editor):
    license_source_type_model = apps.get_model('subscriptions', 'SubscriptionLicenseSourceType')
    for name, slug in LICENSE_SOURCE_TYPES.items():
        license_source_type_model.objects.update_or_create(name=name, slug=slug)


def delete_license_source_types(apps, schema_editor):
    license_source_type_model = apps.get_model('subscriptions', 'SubscriptionLicenseSourceType')
    license_source_type_model.objects.filter(name__in=LICENSE_SOURCE_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0058_subscriptionlicensesource_subscriptionlicensesourcetype'),
    ]

    operations = [
        migrations.RunPython(
            code=add_license_source_types,
            reverse_code=delete_license_source_types
        )

    ]
