# Generated by Django 4.2.8 on 2024-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0062_add_license_transfer_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallicensetransferjob',
            name='transfer_all',
            field=models.BooleanField(default=False, help_text='Set to true to transfer ALL licenses from old to new plan, regardless of status.'),
        ),
        migrations.AddField(
            model_name='licensetransferjob',
            name='transfer_all',
            field=models.BooleanField(default=False, help_text='Set to true to transfer ALL licenses from old to new plan, regardless of status.'),
        ),
        migrations.AlterField(
            model_name='historicallicensetransferjob',
            name='license_uuids_raw',
            field=models.TextField(blank=True, help_text='Delimitted (with newlines by default) list of license_uuids to transfer', null=True),
        ),
        migrations.AlterField(
            model_name='licensetransferjob',
            name='license_uuids_raw',
            field=models.TextField(blank=True, help_text='Delimitted (with newlines by default) list of license_uuids to transfer', null=True),
        ),
    ]
