# Generated by Django 4.2.9 on 2024-01-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0064_subscriptionplan_desired_num_licenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplan',
            name='desired_num_licenses',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Total number of licenses that should exist for this SubscriptionPlan. The total license count (provisioned asynchronously) will reach the desired amount eventually. Empty (NULL) means no attempts will be made to asynchronously provision licenses.', null=True, verbose_name='Desired Number of Licenses'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='desired_num_licenses',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Total number of licenses that should exist for this SubscriptionPlan. The total license count (provisioned asynchronously) will reach the desired amount eventually. Empty (NULL) means no attempts will be made to asynchronously provision licenses.', null=True, verbose_name='Desired Number of Licenses'),
        ),
    ]
