# Generated by Django 4.2.9 on 2024-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0065_subscriptionplan_desired_num_licenses_not_editable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['subscription_plan', 'status'], name='subscription_plan_status_idx'),
        ),
    ]
