# Generated by Django 4.2.13 on 2024-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0068_licenseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragreement',
            name='disable_expiration_notifications',
            field=models.BooleanField(default=False, help_text='Used to disable subscription expiration notifications, and the expiration date in the subsidy summary box in the enterprise learner portal MFE. If the subscription is expired, the subsidy summary box will not display the subscription status with the expired messaging.'),
        ),
        migrations.AlterField(
            model_name='historicalcustomeragreement',
            name='disable_expiration_notifications',
            field=models.BooleanField(default=False, help_text='Used to disable subscription expiration notifications, and the expiration date in the subsidy summary box in the enterprise learner portal MFE. If the subscription is expired, the subsidy summary box will not display the subscription status with the expired messaging.'),
        ),
    ]
