# Generated by Django 4.2.16 on 2024-09-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0069_alter_customeragreement_disable_expiration_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='expired_subscription_modal_messaging',
            field=models.CharField(blank=True, help_text='The content of a modal that will appear to learners upon subscription expiration. This text can be used for custom guidance per customer.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='has_custom_license_expiration_messaging',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has a unique license expiration experience, instead of the standard one.'),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='hyper_link_text_for_expired_modal',
            field=models.CharField(blank=True, help_text='The display text for the link that will be embedded at the end of the custom expiration modal.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='url_for_expired_modal',
            field=models.CharField(blank=True, help_text='The underlying url that will be embedded as a hyperlink at the end of the custom expiration modal.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='expired_subscription_modal_messaging',
            field=models.CharField(blank=True, help_text='The content of a modal that will appear to learners upon subscription expiration. This text can be used for custom guidance per customer.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='has_custom_license_expiration_messaging',
            field=models.BooleanField(default=False, help_text='Indicates if the customer has a unique license expiration experience, instead of the standard one.'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='hyper_link_text_for_expired_modal',
            field=models.CharField(blank=True, help_text='The display text for the link that will be embedded at the end of the custom expiration modal.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='url_for_expired_modal',
            field=models.CharField(blank=True, help_text='The underlying url that will be embedded as a hyperlink at the end of the custom expiration modal.', max_length=512, null=True),
        ),
    ]
