# Generated by Django 4.2.16 on 2024-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0070_customeragreement_expired_subscription_modal_messaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='enable_auto_applied_subscriptions_with_universal_link',
            field=models.BooleanField(default=False, help_text='By default, auto-applied subscriptions are only granted when learners join their enterprise via SSO, checking this box will enable subscription licenses to be applied when a learner joins the enterprise via Universal link as well'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='enable_auto_applied_subscriptions_with_universal_link',
            field=models.BooleanField(default=False, help_text='By default, auto-applied subscriptions are only granted when learners join their enterprise via SSO, checking this box will enable subscription licenses to be applied when a learner joins the enterprise via Universal link as well'),
        ),
    ]
