# Generated by Django 4.2.16 on 2024-10-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0071_customeragreement_enable_auto_applied_subscriptions_with_universal_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='button_label_in_modal',
            field=models.CharField(blank=True, help_text='The text that will appear as on the button in the expiration modal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='modal_header_text',
            field=models.CharField(blank=True, help_text='The bold text that will appear as the header in the expiration modal.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='url_for_button_in_modal',
            field=models.CharField(blank=True, help_text='The URL that should underly the sole button in the expiration modal', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='button_label_in_modal',
            field=models.CharField(blank=True, help_text='The text that will appear as on the button in the expiration modal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='modal_header_text',
            field=models.CharField(blank=True, help_text='The bold text that will appear as the header in the expiration modal.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='url_for_button_in_modal',
            field=models.CharField(blank=True, help_text='The URL that should underly the sole button in the expiration modal', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customeragreement',
            name='expired_subscription_modal_messaging',
            field=models.TextField(blank=True, help_text='The content of a modal that will appear to learners upon subscription expiration. This text can be used for custom guidance per customer.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomeragreement',
            name='expired_subscription_modal_messaging',
            field=models.TextField(blank=True, help_text='The content of a modal that will appear to learners upon subscription expiration. This text can be used for custom guidance per customer.', null=True),
        ),
    ]
