# Generated by Django 4.2.16 on 2024-10-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0072_customeragreement_button_label_in_modal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeragreement',
            name='hyper_link_text_for_expired_modal',
        ),
        migrations.RemoveField(
            model_name='customeragreement',
            name='url_for_expired_modal',
        ),
        migrations.RemoveField(
            model_name='historicalcustomeragreement',
            name='hyper_link_text_for_expired_modal',
        ),
        migrations.RemoveField(
            model_name='historicalcustomeragreement',
            name='url_for_expired_modal',
        ),
    ]
