# Generated by Django 4.2.17 on 2025-02-12 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0074_historicalcustomsubscriptionexpirationmessaging_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='auto_scaling_increment_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage of total licenses in the current plan that will be created when auto-scaling will be executed. For instance, if the number of licenses in the plan is 50,000, and we set this field to 10 percent, an auto-scale execution would result in adding 5,000 licenses to the plan.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='auto_scaling_max_licenses',
            field=models.IntegerField(blank=True, help_text='The maximum number of licenses a plan for this customer is allowed to automatically scale to. Consider setting this to a factor of 3 or 4 of the desired number of licenses for the current plan. For example, if the plan in question has 10,000 desired licenses, set the value of this field to 40,000.', null=True),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='auto_scaling_threshold_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage of allocated (i.e. activated or assigned) licenses in the current plan above which auto-scaling will be executed.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='customeragreement',
            name='enable_auto_scaling_of_current_plan',
            field=models.BooleanField(db_index=True, default=False, help_text='Enables the most current, active plan for this customer to automatically have licenses added to it when the count of allocated licenses hits some threshold. The number of licenses is allowed to scale up to a hard limit, specified by `auto_scaling_max_licenses`.'),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='auto_scaling_increment_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage of total licenses in the current plan that will be created when auto-scaling will be executed. For instance, if the number of licenses in the plan is 50,000, and we set this field to 10 percent, an auto-scale execution would result in adding 5,000 licenses to the plan.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='auto_scaling_max_licenses',
            field=models.IntegerField(blank=True, help_text='The maximum number of licenses a plan for this customer is allowed to automatically scale to. Consider setting this to a factor of 3 or 4 of the desired number of licenses for the current plan. For example, if the plan in question has 10,000 desired licenses, set the value of this field to 40,000.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='auto_scaling_threshold_percentage',
            field=models.IntegerField(blank=True, help_text='Percentage of allocated (i.e. activated or assigned) licenses in the current plan above which auto-scaling will be executed.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='historicalcustomeragreement',
            name='enable_auto_scaling_of_current_plan',
            field=models.BooleanField(db_index=True, default=False, help_text='Enables the most current, active plan for this customer to automatically have licenses added to it when the count of allocated licenses hits some threshold. The number of licenses is allowed to scale up to a hard limit, specified by `auto_scaling_max_licenses`.'),
        ),
    ]
