# Generated by Django 4.2.16 on 2024-10-31 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0074_historicalcustomsubscriptionexpirationmessaging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsubscriptionexpirationmessaging',
            name='customer_agreement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_subscription_expiration_messaging', to='subscriptions.customeragreement'),
        ),
    ]
