# Generated by Django 4.2.17 on 2025-09-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0075_license_auto_scaling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='prior_subscription_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="This is the old/current plan. If you're trying to setup a renewal for Plan A into -> Plan B, then set this field to the uuid for Plan A.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='renewed_subscription_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="This is the new/future plan. If you're trying to setup a renewal for Plan A into -> Plan B, then set this field to the uuid for Plan B.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='prior_subscription_plan',
            field=models.OneToOneField(help_text="This is the old/current plan. If you're trying to setup a renewal for Plan A into -> Plan B, then set this field to the uuid for Plan A.", on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='renewed_subscription_plan',
            field=models.OneToOneField(blank=True, help_text="This is the new/future plan. If you're trying to setup a renewal for Plan A into -> Plan B, then set this field to the uuid for Plan B.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_renewal', to='subscriptions.subscriptionplan'),
        ),
    ]
