# Generated by Django 4.2.16 on 2024-10-31 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0075_alter_customsubscriptionexpirationmessaging_customer_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsubscriptionexpirationmessaging',
            name='customer_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_custom_subscription_expiration_messaging', to='subscriptions.customeragreement'),
        ),
    ]
