# Generated by Django 4.2.25 on 2025-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0076_renewal_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplanrenewal',
            name='exempt_from_batch_processing',
            field=models.BooleanField(default=False, help_text='Whether auto-applied licenses should be disabled for the future plan. If the original plan was not auto applying licenses, modifying this field will have no effect.'),
        ),
        migrations.AddField(
            model_name='subscriptionplanrenewal',
            name='exempt_from_batch_processing',
            field=models.BooleanField(default=False, help_text='Whether auto-applied licenses should be disabled for the future plan. If the original plan was not auto applying licenses, modifying this field will have no effect.'),
        ),
    ]
