# Generated by Django 4.2.25 on 2025-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0076_renewal_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscriptionplanrenewal',
            name='exempt_from_batch_processing',
            field=models.BooleanField(default=False, help_text='We do not want the cron to process SSP renewals linking the trial plan to the paid plan. It will instead be kicked off by the subscription state change. '),
        ),
        migrations.AddField(
            model_name='subscriptionplanrenewal',
            name='exempt_from_batch_processing',
            field=models.BooleanField(default=False, help_text='We do not want the cron to process SSP renewals linking the trial plan to the paid plan. It will instead be kicked off by the subscription state change. '),
        ),
    ]
