# Generated by Django 4.2.19 on 2025-11-03 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0077_historicalsubscriptionplanrenewal_exempt_from_batch_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubscriptionplanrenewal',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Copy of the Opportunity Line Item ID field (18 characters) pertaining to the renewed subscription plan.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='Salesforce Opportunity Line Item'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrenewal',
            name='salesforce_opportunity_id',
            field=models.CharField(blank=True, help_text='Copy of the Opportunity Line Item ID field (18 characters) pertaining to the renewed subscription plan.', max_length=18, null=True, validators=[django.core.validators.MinLengthValidator(18)], verbose_name='Salesforce Opportunity Line Item'),
        ),
    ]
