name: Django CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
        - "py312-django42"
        - "py312-django52"
        - "translations"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true
        python-version: '3.12'

    - name: Install Dependencies
      run: uv sync --group ci

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: uv run tox

    - name: Codecov
      if: startsWith(matrix.toxenv, 'py312-django')
      run: uv run --with codecov codecov

  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
        - "quality"
        - "pii_check"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true
        python-version: '3.12'

    - name: Install Dependencies
      run: uv sync --group ci

    - name: Run Checks
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: uv run tox
