name: Build and Push Docker Image

on:
  push:
    branches:
      - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: jwalton/gh-find-current-pr@v1.0.2
        id: findPr
        with:
          github-token: ${{ secrets.EDX_DEPLOYMENT_GH_TOKEN }}

      - name: Build and Push docker image
        run : ./.github/workflows/deployment_prs.sh
        if: success() && steps.findPr.outputs.number
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          PR_TITLE: ${{ steps.findPr.outputs.title }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GH_ACCESS_TOKEN: ${{ secrets.EDX_DEPLOYMENT_GH_TOKEN }}
